profile_project/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'sign_in/$', views.sign_in, name='sign_in'),
    url(r'sign_up/$', views.sign_up, name='sign_up'),
    url(r'sign_out/$', views.sign_out, name='sign_out'),
    url(r'profile/$', views.profile_detail, name='profile'),
    url(r'profile/edit/$', views.edit_profile, name='edit'),
    url(r'profile/change_password/$', views.change_password,
        name='change_password'),
]

profile_project/project_7/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', views.home, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=16)
    last_name = models.CharField(max_length=16)
    email = models.EmailField()
    confirm_email = models.EmailField()
    dob = models.DateField(
        null=True,
        blank=True,
        verbose_name="Date of birth")
    bio = models.TextField()
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

profile_project/accounts/forms.py
import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


from . import models
import datetime


class ProfileForm(forms.ModelForm):
    confirm_email = forms.EmailField(
        label="confirm email",
        required=True
    )

    bio = forms.CharField(widget=forms.Textarea, 
                          min_length=10, 
                          label="biography")

    class Meta:
        model = models.Profile
        fields = [
            'first_name',
            'last_name',
            'email',
            'confirm_email',
            'dob',
            'bio',
            'avatar'
        ]

    def clean(self):
        """check that both email given in verification are identicle"""
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        verify = cleaned_data.get('confirm_email')

        if email != verify:
            raise forms.ValidationError("Emails do not match!")

profile_project/accounts/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm,
    PasswordChangeForm)
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect


from . import models
from . import forms


def sign_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            if form.user_cache is not None:
                user = form.user_cache
                if user.is_active:
                    login(request, user)
                    return redirect('accounts:profile')
                else:
                    messages.error(
                        request,
                        "That user account has been disabled."
                    )
            else:
                messages.error(
                    request,
                    "Username or password is incorrect."
                )
    return render(request, 'accounts/sign_in.html', {'form': form})


def sign_up(request):
    form = UserCreationForm()
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1']
            )
            login(request, user)
            messages.success(
                request,
                "You're now a user! Time to create your profile."
            )
            return redirect('accounts:edit')
    return render(request, 'accounts/sign_up.html', {'form': form})


def sign_out(request):
    logout(request)
    messages.success(request, "You've been signed out. Come back soon!")
    return HttpResponseRedirect(reverse('home'))


@login_required
def profile_detail(request):
    profile = request.user.profile
    return render(request, 'accounts/profile.html', {'profile': profile})

@login_required
def edit_profile(request):
    form = forms.ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        form = forms.ProfileForm(
                data=request.POST,
                instance=request.user.profile,
                files=request.FILES
        )
        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
    return render(request, 'accounts/edit_profile.html', {'form': form})


# https://simpleisbetterthancomplex.com/tips/2016/08/04/django-tip-9-password-change-form.html
# this site helped with forming the following code.
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            password = form.cleaned_data['new_password1']
            if request.user.check_password(password):
                messages.error(request,
                "Password must differ from your current password!")
                return HttpResponseRedirect(
                    reverse('accounts:change_password'))
            else:
                user = form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Your new password has been saved.')
                return redirect('/accounts/profile')
        else:
            messages.error(request,
                'Please make sure your password complies with the requirements below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form': form})

profile_project/project_7/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

profile_project/accounts/templates/accounts/change_password.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Change Password | {{ user.username }}{% endblock %}

{% block body %}
	<form method='POST' enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="button" value="Save">
	</form>
{% endblock %}

profile_project/accounts/templates/accounts/edit_profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block title %}Edit Profile | {{ user.username }}{% endblock %}

{% block body %}
	<form method='POST' enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" class="button" value="Save">
	</form>
{% endblock %}

profile_project/accounts/templates/accounts/profile.html
{% extends "layout.html" %}
{% load static from staticfiles %}


{% block title %}User Profile | {{ user.username }}{% endblock %}

{% block body %}
<div class="grid-25">	
</div>
<div class="grid-75">
	<h2>{{ user.username }}</h2>
	{% if user.profile.avatar %}
	<div>
		<img src="{{ user.profile.avatar.url }}">
	</div>
	{% else %}
	<p>No photo available</p>
	{% endif %}
	<table>
        <tr><td>Name:</td> <td>{{ user.profile.first_name }} {{ user.profile.last_name }}</td></tr>
		<tr><td>Email:</td> <td>{{ user.profile.email }}</td></tr>
		<tr><td>Date of Birth:</td> <td>{{ user.profile.dob }}</td></tr>
		<tr><td>Bio:</td> <td>{{ user.profile.bio }}</td></tr>
	</table>
	<form action="{% url 'accounts:edit' %}">
		<button type="submit">Edit</button>
	</form>
	<form action="{% url 'accounts:change_password' %}">
		<button type="submit">Change Password</button>
	</form>
</div>
{% endblock %}

profile_project/accounts/templates/accounts/sign_in.html
{% extends "layout.html" %}

{% block title %}Sign In | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign In">
</form>
{% endblock %}

profile_project/accounts/templates/accounts/sign_up.html
{% extends "layout.html" %}

{% block title %}Sign Up | {{ super }}{% endblock %}

{% block body %}
<form method="POST" action="{% url 'accounts:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button-primary" value="Sign Up">
</form>
{% endblock %}

profile_project/templates/home.html
{% extends 'layout.html' %}

{% block body %}
    <div class="grid-25">
        nav here maybe?
    </div>
    <div class="grid-75">
        <h1>Welcome!</h1>
        <p>1</p>
        <p>2</p>
    </div>
{% endblock %}

profile_project/templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>{% block title %}Circle{% endblock %}</title>

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static "css/global.css" %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static "js/autogrow.js" %}"></script>
    <script type="text/javascript" src="{% static "js/global.js" %}"></script>


</head>
<body>
<header class="circle--header">
    <div class="bounds">
        <div class="circle--fluid">
            <div class="circle--fluid--cell">
                <h1 class="hide-text circle--logo"><a class="logo"
                                                      href="{% url 'home' %}">Circle</a>
                </h1>
            </div>
            <div class="circle--fluid--cell circle--fluid--primary">
                <nav>
                    <ul class="circle--inline">
                        <li><a href="#">nav</a></li>
                        <li><a href="#">here?</a></li>
                    </ul>
                </nav>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <nav>
                    <ul class="circle--inline">
                        {% if not user.is_authenticated %}
                            <li><a href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                            <li><a href="{% url 'accounts:sign_in' %}">Sign In</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:profile' %}">View Profile</a></li>                            
                            <li><a href="{% url 'accounts:sign_out' %}">Sign Out</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</header>

<div class="bounds circle--page">
    {% if messages %}
        <ul class="messages centered grid-50">
            {% for message in messages %}
                <li{% if message.tags %}
                    class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% block body %}{% endblock %}
</div>
</body>
</html>